{
 "title": "Flask OpenTelemetry Dashboard",
 "tags": [
  "flask",
  "opentelemetry"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "HTTP Server Active Requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "http_server_active_requests{service_name=\"simple-flask-app\"}",
     "legendFormat": "Active Requests"
    }
   ]
  },
  {
   "title": "Process CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total{service_name=\"simple-flask-app\"}[1m])",
     "legendFormat": "CPU Usage"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "process_resident_memory_bytes{service_name=\"simple-flask-app\"}",
     "legendFormat": "Resident Memory"
    },
    {
     "expr": "process_virtual_memory_bytes{service_name=\"simple-flask-app\"}",
     "legendFormat": "Virtual Memory"
    }
   ]
  },
  {
   "title": "Python GC Collections",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "python_gc_collections_total{service_name=\"simple-flask-app\"}",
     "legendFormat": "Generation {{generation}}"
    }
   ]
  }
 ]
}