apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: scaledjobs.keda.sh
  labels:
    app.kubernetes.io/part-of: keda-operator
spec:
  group: keda.sh
  versions:
    - name: v1alpha1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                jobTargetRef:
                  type: object
                  properties:
                    parallelism:
                      type: integer
                      minimum: 1
                    completions:
                      type: integer
                      minimum: 1
                    activeDeadlineSeconds:
                      type: integer
                    backoffLimit:
                      type: integer
                    template:
                      type: object
                  required:
                    - template
                pollingInterval:
                  type: integer
                  minimum: 1
                successfulJobsHistoryLimit:
                  type: integer
                  minimum: 0
                failedJobsHistoryLimit:
                  type: integer
                  minimum: 0
                envSourceContainerName:
                  type: string
                rolloutStrategy:
                  type: string
                  enum:
                    - Default
                    - RollingUpdate
                    - Recreate
                scalingStrategy:
                  type: object
                  properties:
                    strategy:
                      type: string
                      enum:
                        - default
                        - custom
                        - accurate
                    customScalingQueueLengthDeduction:
                      type: integer
                    customScalingRunningJobPercentage:
                      type: integer
                      minimum: 1
                      maximum: 100
                    pendingPodConditions:
                      type: array
                      items:
                        type: string
                    multipleScalersCalculation:
                      type: string
                      enum:
                        - "max"
                        - "min"
                        - "avg"
                        - "sum"
                triggers:
                  type: array
                  items:
                    type: object
                    properties:
                      type:
                        type: string
                      name:
                        type: string
                      metadata:
                        type: object
                        additionalProperties:
                          type: string
                      authenticationRef:
                        type: object
                        properties:
                          name:
                            type: string
                          kind:
                            type: string
                            enum:
                              - TriggerAuthentication
                              - ClusterTriggerAuthentication
                      metricType:
                        type: string
                        enum:
                          - AverageValue
                          - Value
                          - Utilization
                      metadata:
                        type: object
                        additionalProperties:
                          type: string
                    required:
                      - type
                fallback:
                  type: object
                  properties:
                    failureThreshold:
                      type: integer
                      minimum: 1
                    replicas:
                      type: integer
                      minimum: 0
                  required:
                    - failureThreshold
                    - replicas
              required:
                - jobTargetRef
                - triggers
            status:
              type: object
              properties:
                conditions:
                  type: array
                  items:
                    type: object
                    properties:
                      type:
                        type: string
                      status:
                        type: string
                      reason:
                        type: string
                      message:
                        type: string
                      lastTransitionTime:
                        type: string
                health:
                  type: object
                  additionalProperties:
                    type: object
                    properties:
                      numberOfFailures:
                        type: integer
                      status:
                        type: string
                lastActiveTime:
                  type: string
  names:
    kind: ScaledJob
    plural: scaledjobs
    singular: scaledjob
    categories:
      - all
      - keda
  scope: Namespaced
