apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - karpenter.yaml
#  - node-class.yaml
#  - node-pools.yaml

namespace: argocd

labels:
  - pairs:
      app.kubernetes.io/part-of: infrastructure
      app.kubernetes.io/managed-by: argocd