http:
  timeout: 10000
  keepAlive:
    enabled: false
  minTlsVersion: TLS13
prometheus:
  metricServer:
    enabled: true
    port: 8080
    portName: metrics
    serviceMonitor:
      enabled: true
  operator:
    enabled: true
    port: 8080
    serviceMonitor:
      enabled: true
