apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: keda
  namespace: keda
spec:
  interval: 5m
  chart:
    spec:
      chart: keda
      version: "2.13.2"
      sourceRef:
        kind: HelmRepository
        name: kedacore
        namespace: keda
      interval: 1m
  valuesFrom:
    - kind: ConfigMap
      name: config-keda
      valuesKey: values.yaml
      optional: false
