apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: keda
  namespace: argocd
  labels:
    team: infrastructure
    app: keda
spec:
  project: infrastructure
  source:
    repoURL: "https://kedacore.github.io/charts"
    chart: keda
    targetRevision: 2.14.0          # última GA
    helm:
      values: |
        operator:
          replicaCount: 1
        resources:
          limits:
            cpu: 200m
            memory: 256Mi
          requests:
            cpu: 100m
            memory: 128Mi
  destination:
    server: https://kubernetes.default.svc
    namespace: keda
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
