apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: keda
  namespace: keda
  labels:
    team: infrastructure
    app: keda
spec:
  project: infrastructure
  source:
    chart: keda
    repoURL: https://kedacore.github.io/charts
    targetRevision: 2.13.2
    helm:
      values: |
        http:
          timeout: 10000
          keepAlive:
            enabled: false
          minTlsVersion: TLS13
        prometheus:
          metricServer:
            enabled: true
            port: 8080
            portName: metrics
            serviceMonitor:
              enabled: true
          operator:
            enabled: true
            port: 8080
            serviceMonitor:
              enabled: true
  destination:
    server: https://kubernetes.default.svc
    namespace: keda
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
