# === Namespace =========================================================
apiVersion: v1
kind: Namespace
metadata:
  name: keda
---
# === CRDs + Controller + Metrics adapter ===============================
# Descargados del release v2.14.0 y consolidados para brevedad
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: scaledobjects.keda.sh
  labels: { app.kubernetes.io/name: keda }
spec:
  group: keda.sh
  names:
    kind: ScaledObject
    plural: scaledobjects
    singular: scaledobject
  scope: Namespaced
  versions:
    - name: v1alpha1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          x-kubernetes-preserve-unknown-fields: true
---
# (repite CRDs para ScaledJob, TriggerAuthentication, ClusterTriggerAuthentication, etc.)
# ...
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: keda-operator
  namespace: keda
  labels:
    app.kubernetes.io/name: keda-operator
spec:
  replicas: 1
  selector:
    matchLabels: { app.kubernetes.io/name: keda-operator }
  template:
    metadata:
      labels: { app.kubernetes.io/name: keda-operator }
    spec:
      serviceAccountName: keda-operator
      containers:
        - name: keda
          image: ghcr.io/kedacore/keda:2.14.0
          args:
            - "--cert-dir=/tmp/k8s-webhook-server/serving-certs"
            - "--webhook-port=9443"
          ports:
            - containerPort: 8080
              name: metrics
            - containerPort: 9443
              name: admission
---
apiVersion: v1
kind: Service
metadata:
  name: keda-metrics-apiserver
  namespace: keda
spec:
  selector:
    app.kubernetes.io/name: keda-operator
  ports:
    - name: https
      port: 443
      targetPort: 8080
---
kind: ServiceAccount
apiVersion: v1
metadata:
  name: keda-operator
  namespace: keda
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: keda-operator
rules:
  - apiGroups: ["*"]
    resources: ["*"]
    verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: keda-operator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: keda-operator
subjects:
  - kind: ServiceAccount
    name: keda-operator
    namespace: keda
