apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - flask-otel-app-2.yaml
  - service-monitor-2.yaml
  - service-patch-2.yaml
  - grafana-dashboard-cm-2.yaml
  - keda-scaledobject-2.yaml

namespace: dev

labels:
  - pairs:
      app.kubernetes.io/part-of: infrastructure
      app.kubernetes.io/managed-by: argocd
