apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: frontapplications.kro.run
spec:
  group: kro.run
  names:
    kind: Frontapplication
    plural: frontapplications
    singular: frontapplication
    shortNames:
      - fa
  scope: Namespaced
  versions:
    - name: v1alpha1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                name:
                  type: string
                image:
                  type: string
                namespace:
                  type: string
                containerport:
                  type: integer
                service:
                  type: object
                  properties:
                    enabled:
                      type: boolean
                    serviceport:
                      type: integer
                    protocol:
                      type: string
                autoscaling:
                  type: object
                  properties:
                    enabled:
                      type: boolean
