apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kro
  namespace: kro
  labels:
    team: infrastructure
    app: kro
spec:
  project: infrastructure
  source:
    chart: kro
    repoURL: ghcr.io/kro-run/kro
    targetRevision: 0.3.0
    helm:
      values: |
  destination:
    server: https://kubernetes.default.svc
    namespace: kro
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
