apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus-stack
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: infrastructure
  source:
    repoURL: https://prometheus-community.github.io/helm-charts
    targetRevision: 69.7.2
    chart: kube-prometheus-stack
    helm:
      values: |
        nameOverride: "metrics-stack"
        fullnameOverride: "metrics-stack"
        namespaceOverride: "monitoring"

        grafana:
          namespaceOverride: "monitoring"
          ingress:
            enabled: true
            ingressClassName: nginx
            annotations:
              nginx.ingress.kubernetes.io/enable-access-log: "true"
              nginx.ingress.kubernetes.io/use-regex: "true"
              nginx.ingress.kubernetes.io/proxy-body-size: 10m
        
        kube-state-metrics:
          namespaceOverride: "monitoring"

        prometheus-node-exporter:
          namespaceOverride: "monitoring"
        additionalServiceMonitors:
        - name: otel-collector-svcmonitor
          namespace: monitoring
          selector:
            matchLabels:
              app.kubernetes.io/name: opentelemetry-collector
          endpoints:
            - port: 8888
              path: /metrics
        additionalPodMonitors:
          - name: otel-collector-podmonitor
            namespace: monitoring
            selector:
              matchLabels:
                app.kubernetes.io/name: opentelemetry-collector
            endpoints:
              - port: 8889
                path: /metrics
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
