apiVersion: v1
kind: Service
metadata:
  name: prometheus-k8s-lb
  namespace: monitoring
  annotations:
    service.beta.kubernetes.io/azure-pip-name: prometheus-ui-pip
spec:
  type: LoadBalancer
  selector:
    app.kubernetes.io/name: prometheus
    prometheus: k8s
  ports:
    - name: web
      port: 9090
      targetPort: web
      protocol: TCP
