apiVersion: kro.run/v1alpha1
kind: Frontapplication # Tipo de Custom Resource
metadata:
  name: flask-otel-app # Nombre único del CR
spec:
  name: flask-otel-app # Prefijo usado en Deployment y Service
  image: juanmarulanda/flask-otel-app:latest # Imagen de Docker Hub
  namespace: dev
  containerport: 5000 # Puerto que expone el contenedor
  service: # Service asociado
    enabled: true # Se crea automáticamente
    serviceport: 5000 # Puerto expuesto por el Service
    protocol: TCP # Protocolo
  autoscaling:
    enabled: false
