apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-otel-app
  namespace: dev
spec:
  selector:
    matchLabels:
      app: flask-otel-app
  template:
    metadata:
      labels:
        app: flask-otel-app
    spec:
      containers:
      - name: flask-otel-app
        image: juanmarulanda/flask-otel-app:latest
        ports:
        - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: flask-otel-app-service
  namespace: dev
spec:
  selector:
    app: flask-otel-app
  ports:
  - protocol: TCP
    port: 5000
    targetPort: 5000
