apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  #- flask-otel-app.yaml

namespace: argocd

labels:
  - pairs:
      app.kubernetes.io/part-of: infrastructure
      app.kubernetes.io/managed-by: argocd
