apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - flask-otel-app.yaml
  - service-monitor.yaml
  - service-patch.yaml
  - grafana-dashboard-cm.yaml

namespace: dev

labels:
  - pairs:
      app.kubernetes.io/part-of: infrastructure
      app.kubernetes.io/managed-by: argocd
