apiVersion: v1
kind: Service
metadata:
  name: flask-otel-app-service
  namespace: dev
  labels:
    app: flask-otel-app
spec:
  ports:
  - name: http
    port: 5000
    protocol: TCP
    targetPort: 5000
